### ISSUE TITLE
monorepo is more than just `package.json`

### ISSUE THREAD

**Issue by zmzlois** [earthly/website#770]
In the [Building a monorepo with Bazel](https://github.com/earthly/website/blob/7ac96b1dbfc4e3cde77df62ff35c2d156ccb4189/blog/_posts/2021-05-11-monorepo-with-bazel.md?plain=1#L35) and [Building a monorepo with Lerna](https://github.com/earthly/website/blob/7ac96b1dbfc4e3cde77df62ff35c2d156ccb4189/blog/_posts/2023-04-03-javascript-monorepo-with-lerna.md?plain=1#L277) you have both used the wording `monorepo is like a single package.json` . 

It is not and far from it. If people doesn't have any knowledge about monorepo this confuses them and miseducate the user. 

Recommend to replace it with `In a monorepo, you will have the power to manage all the modules and dependencies, centralised. With the complexity adds up, you can imagine it has a file like `package.json`, but it is far more powerful. Debugging monorepo specific issue will come different. However the mental model might be similar. `

**Comment by adamgordonbell** [comment]
Hi @zmzlois ,
I can see how this wording could be more clear. Do you want to put together a PR?
